dist: xenial

language: generic

python:
  - 3.6

php:
  - 7.3

services:
  - sqlite3

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

install:
  - sudo apt-get install -y python3 python3-pip php7.3 php7.3-sqlite3 php7.2-sqlite3
  - pip3 install selenium --user
  - php -v

before_script:
  - cp db-template.db tests/resources/db-template.db
  - cp .env.ui.test .env
  - composer update
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan migrate --no-interaction --force
  - php artisan serve --env=ui.test & 

script:
  - pwd
  - google-chrome --version
  - python3 main.py -v
  - ps aux | grep "db-project/server.php" | head -1 | awk '{print $2}' | xargs kill -9
