dist: xenial

language: node_js

python:
  - 3.6

php:
  - 7.3

node_js:
  - 12

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

install:
  - sudo apt-get install -y python3 python3-pip
  - pip3 install selenium --user
  - phpenv global 7.3 2>/dev/null
  - composer self-update
  - ./download_chromedriver.sh
  - node -v
  - php7.3 -v
  - ./chromedriver --version
  - composer install
  - npm install

script:
  - npm build
  - composer dump-autoload
