dist: precise

language: php

php:
  - 7.3

services:
  - sqlite

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - composer travis-tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
