dist: xenial

language: php

python:
  - 3.6

php:
  - 7.3

node_js:
  - 12

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip libxml2-dev nasm
  - nvm install 12
  - pip3 install selenium --user
  - ./download_chromedriver.sh
  - composer self-update

install:
  - node -v
  - php -v
  - ./chromedriver --version
  - composer install
  - npm install

script:
  - npm build
  - composer dump-autoload
