dist: xenial

language: php

python:
  - 3.6

php:
  - 7.3

node_js:
  - 12

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

install:
  - sudo apt-get install -y python3 python3-pip php-common php7.3 php7.3-cli php7.3-common php7.3-fpm php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache php7.3-readline php7.3-xml php-xdebug
  - pip3 install selenium --user
  - composer self-update
  - ./download_chromedriver.sh
  - node -v
  - php7.3 -v
  - ./chromedriver --version
  - composer install
  - npm install

script:
  - npm build
  - composer dump-autoload
