dist: precise

language: python

python:
  - 3.6

install:
  - pip3 install selenium

before_script:
  - cp db-template.db tests/resources/db-template.db
  - php artisan serve --env=ui.test &

script:
  - ./main.py -v
  - ps aux | grep "db-project/server.php" | head -1 | awk '{print $2}' | xargs kill -9
