dist: trusty

language: generic

python:
  - 3.6

php:
  - 7.3

install:
  - pip3 install selenium

before_script:
  - cp db-template.db tests/resources/db-template.db
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan serve --env=ui.test &

script:
  - pwd
  - python3 main.py -v
  - ps aux | grep "db-project/server.php" | head -1 | awk '{print $2}' | xargs kill -9
